/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'telosb_serial_msg'
 * message type.
 */

package blah.foo;

public class telosb_serial_msg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 60;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 101;

    /** Create a new telosb_serial_msg of size 60. */
    public telosb_serial_msg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new telosb_serial_msg of the given data_length. */
    public telosb_serial_msg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new telosb_serial_msg with the given data_length
     * and base offset.
     */
    public telosb_serial_msg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new telosb_serial_msg using the given byte array
     * as backing store.
     */
    public telosb_serial_msg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new telosb_serial_msg using the given byte array
     * as backing store, with the given base offset.
     */
    public telosb_serial_msg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new telosb_serial_msg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public telosb_serial_msg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new telosb_serial_msg embedded in the given message
     * at the given base offset.
     */
    public telosb_serial_msg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new telosb_serial_msg embedded in the given message
     * at the given base offset and length.
     */
    public telosb_serial_msg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <telosb_serial_msg> \n";
      try {
        s += "  [raw_voltage_monitoramento="+Float.toString(get_raw_voltage_monitoramento())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_voltage_analise="+Float.toString(get_raw_voltage_analise())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_voltage_planejamento="+Float.toString(get_raw_voltage_planejamento())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_voltage_execucao="+Float.toString(get_raw_voltage_execucao())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_voltage_geral="+Float.toString(get_raw_voltage_geral())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_temperature=0x"+Long.toHexString(get_raw_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_voltage=0x"+Long.toHexString(get_raw_voltage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_msg_number=0x"+Long.toHexString(get_raw_msg_number())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_node_ID=0x"+Long.toHexString(get_raw_node_ID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_voltage_monitoramento="+Float.toString(get_converted_voltage_monitoramento())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_voltage_analise="+Float.toString(get_converted_voltage_analise())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_voltage_planejamento="+Float.toString(get_converted_voltage_planejamento())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_voltage_execucao="+Float.toString(get_converted_voltage_execucao())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_voltage_geral="+Float.toString(get_converted_voltage_geral())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_temperature="+Float.toString(get_converted_temperature())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [converted_voltage="+Float.toString(get_converted_voltage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [msg_number=0x"+Long.toHexString(get_msg_number())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [node_ID=0x"+Long.toHexString(get_node_ID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_voltage_monitoramento
    //   Field type: float, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_voltage_monitoramento' is signed (false).
     */
    public static boolean isSigned_raw_voltage_monitoramento() {
        return false;
    }

    /**
     * Return whether the field 'raw_voltage_monitoramento' is an array (false).
     */
    public static boolean isArray_raw_voltage_monitoramento() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_voltage_monitoramento'
     */
    public static int offset_raw_voltage_monitoramento() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_voltage_monitoramento'
     */
    public static int offsetBits_raw_voltage_monitoramento() {
        return 0;
    }

    /**
     * Return the value (as a float) of the field 'raw_voltage_monitoramento'
     */
    public float get_raw_voltage_monitoramento() {
        return (float)getFloatElement(offsetBits_raw_voltage_monitoramento(), 32);
    }

    /**
     * Set the value of the field 'raw_voltage_monitoramento'
     */
    public void set_raw_voltage_monitoramento(float value) {
        setFloatElement(offsetBits_raw_voltage_monitoramento(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_voltage_monitoramento'
     */
    public static int size_raw_voltage_monitoramento() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_voltage_monitoramento'
     */
    public static int sizeBits_raw_voltage_monitoramento() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_voltage_analise
    //   Field type: float, unsigned
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_voltage_analise' is signed (false).
     */
    public static boolean isSigned_raw_voltage_analise() {
        return false;
    }

    /**
     * Return whether the field 'raw_voltage_analise' is an array (false).
     */
    public static boolean isArray_raw_voltage_analise() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_voltage_analise'
     */
    public static int offset_raw_voltage_analise() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_voltage_analise'
     */
    public static int offsetBits_raw_voltage_analise() {
        return 32;
    }

    /**
     * Return the value (as a float) of the field 'raw_voltage_analise'
     */
    public float get_raw_voltage_analise() {
        return (float)getFloatElement(offsetBits_raw_voltage_analise(), 32);
    }

    /**
     * Set the value of the field 'raw_voltage_analise'
     */
    public void set_raw_voltage_analise(float value) {
        setFloatElement(offsetBits_raw_voltage_analise(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_voltage_analise'
     */
    public static int size_raw_voltage_analise() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_voltage_analise'
     */
    public static int sizeBits_raw_voltage_analise() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_voltage_planejamento
    //   Field type: float, unsigned
    //   Offset (bits): 64
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_voltage_planejamento' is signed (false).
     */
    public static boolean isSigned_raw_voltage_planejamento() {
        return false;
    }

    /**
     * Return whether the field 'raw_voltage_planejamento' is an array (false).
     */
    public static boolean isArray_raw_voltage_planejamento() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_voltage_planejamento'
     */
    public static int offset_raw_voltage_planejamento() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_voltage_planejamento'
     */
    public static int offsetBits_raw_voltage_planejamento() {
        return 64;
    }

    /**
     * Return the value (as a float) of the field 'raw_voltage_planejamento'
     */
    public float get_raw_voltage_planejamento() {
        return (float)getFloatElement(offsetBits_raw_voltage_planejamento(), 32);
    }

    /**
     * Set the value of the field 'raw_voltage_planejamento'
     */
    public void set_raw_voltage_planejamento(float value) {
        setFloatElement(offsetBits_raw_voltage_planejamento(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_voltage_planejamento'
     */
    public static int size_raw_voltage_planejamento() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_voltage_planejamento'
     */
    public static int sizeBits_raw_voltage_planejamento() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_voltage_execucao
    //   Field type: float, unsigned
    //   Offset (bits): 96
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_voltage_execucao' is signed (false).
     */
    public static boolean isSigned_raw_voltage_execucao() {
        return false;
    }

    /**
     * Return whether the field 'raw_voltage_execucao' is an array (false).
     */
    public static boolean isArray_raw_voltage_execucao() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_voltage_execucao'
     */
    public static int offset_raw_voltage_execucao() {
        return (96 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_voltage_execucao'
     */
    public static int offsetBits_raw_voltage_execucao() {
        return 96;
    }

    /**
     * Return the value (as a float) of the field 'raw_voltage_execucao'
     */
    public float get_raw_voltage_execucao() {
        return (float)getFloatElement(offsetBits_raw_voltage_execucao(), 32);
    }

    /**
     * Set the value of the field 'raw_voltage_execucao'
     */
    public void set_raw_voltage_execucao(float value) {
        setFloatElement(offsetBits_raw_voltage_execucao(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_voltage_execucao'
     */
    public static int size_raw_voltage_execucao() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_voltage_execucao'
     */
    public static int sizeBits_raw_voltage_execucao() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_voltage_geral
    //   Field type: float, unsigned
    //   Offset (bits): 128
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_voltage_geral' is signed (false).
     */
    public static boolean isSigned_raw_voltage_geral() {
        return false;
    }

    /**
     * Return whether the field 'raw_voltage_geral' is an array (false).
     */
    public static boolean isArray_raw_voltage_geral() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_voltage_geral'
     */
    public static int offset_raw_voltage_geral() {
        return (128 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_voltage_geral'
     */
    public static int offsetBits_raw_voltage_geral() {
        return 128;
    }

    /**
     * Return the value (as a float) of the field 'raw_voltage_geral'
     */
    public float get_raw_voltage_geral() {
        return (float)getFloatElement(offsetBits_raw_voltage_geral(), 32);
    }

    /**
     * Set the value of the field 'raw_voltage_geral'
     */
    public void set_raw_voltage_geral(float value) {
        setFloatElement(offsetBits_raw_voltage_geral(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_voltage_geral'
     */
    public static int size_raw_voltage_geral() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_voltage_geral'
     */
    public static int sizeBits_raw_voltage_geral() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_temperature
    //   Field type: int, unsigned
    //   Offset (bits): 160
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_temperature' is signed (false).
     */
    public static boolean isSigned_raw_temperature() {
        return false;
    }

    /**
     * Return whether the field 'raw_temperature' is an array (false).
     */
    public static boolean isArray_raw_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_temperature'
     */
    public static int offset_raw_temperature() {
        return (160 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_temperature'
     */
    public static int offsetBits_raw_temperature() {
        return 160;
    }

    /**
     * Return the value (as a int) of the field 'raw_temperature'
     */
    public int get_raw_temperature() {
        return (int)getUIntBEElement(offsetBits_raw_temperature(), 16);
    }

    /**
     * Set the value of the field 'raw_temperature'
     */
    public void set_raw_temperature(int value) {
        setUIntBEElement(offsetBits_raw_temperature(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_temperature'
     */
    public static int size_raw_temperature() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_temperature'
     */
    public static int sizeBits_raw_temperature() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_voltage
    //   Field type: int, unsigned
    //   Offset (bits): 176
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_voltage' is signed (false).
     */
    public static boolean isSigned_raw_voltage() {
        return false;
    }

    /**
     * Return whether the field 'raw_voltage' is an array (false).
     */
    public static boolean isArray_raw_voltage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_voltage'
     */
    public static int offset_raw_voltage() {
        return (176 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_voltage'
     */
    public static int offsetBits_raw_voltage() {
        return 176;
    }

    /**
     * Return the value (as a int) of the field 'raw_voltage'
     */
    public int get_raw_voltage() {
        return (int)getUIntBEElement(offsetBits_raw_voltage(), 16);
    }

    /**
     * Set the value of the field 'raw_voltage'
     */
    public void set_raw_voltage(int value) {
        setUIntBEElement(offsetBits_raw_voltage(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_voltage'
     */
    public static int size_raw_voltage() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_voltage'
     */
    public static int sizeBits_raw_voltage() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_msg_number
    //   Field type: int, unsigned
    //   Offset (bits): 192
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_msg_number' is signed (false).
     */
    public static boolean isSigned_raw_msg_number() {
        return false;
    }

    /**
     * Return whether the field 'raw_msg_number' is an array (false).
     */
    public static boolean isArray_raw_msg_number() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_msg_number'
     */
    public static int offset_raw_msg_number() {
        return (192 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_msg_number'
     */
    public static int offsetBits_raw_msg_number() {
        return 192;
    }

    /**
     * Return the value (as a int) of the field 'raw_msg_number'
     */
    public int get_raw_msg_number() {
        return (int)getUIntBEElement(offsetBits_raw_msg_number(), 16);
    }

    /**
     * Set the value of the field 'raw_msg_number'
     */
    public void set_raw_msg_number(int value) {
        setUIntBEElement(offsetBits_raw_msg_number(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_msg_number'
     */
    public static int size_raw_msg_number() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_msg_number'
     */
    public static int sizeBits_raw_msg_number() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_node_ID
    //   Field type: int, unsigned
    //   Offset (bits): 208
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_node_ID' is signed (false).
     */
    public static boolean isSigned_raw_node_ID() {
        return false;
    }

    /**
     * Return whether the field 'raw_node_ID' is an array (false).
     */
    public static boolean isArray_raw_node_ID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_node_ID'
     */
    public static int offset_raw_node_ID() {
        return (208 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_node_ID'
     */
    public static int offsetBits_raw_node_ID() {
        return 208;
    }

    /**
     * Return the value (as a int) of the field 'raw_node_ID'
     */
    public int get_raw_node_ID() {
        return (int)getUIntBEElement(offsetBits_raw_node_ID(), 16);
    }

    /**
     * Set the value of the field 'raw_node_ID'
     */
    public void set_raw_node_ID(int value) {
        setUIntBEElement(offsetBits_raw_node_ID(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_node_ID'
     */
    public static int size_raw_node_ID() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_node_ID'
     */
    public static int sizeBits_raw_node_ID() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_voltage_monitoramento
    //   Field type: float, unsigned
    //   Offset (bits): 224
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_voltage_monitoramento' is signed (false).
     */
    public static boolean isSigned_converted_voltage_monitoramento() {
        return false;
    }

    /**
     * Return whether the field 'converted_voltage_monitoramento' is an array (false).
     */
    public static boolean isArray_converted_voltage_monitoramento() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_voltage_monitoramento'
     */
    public static int offset_converted_voltage_monitoramento() {
        return (224 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_voltage_monitoramento'
     */
    public static int offsetBits_converted_voltage_monitoramento() {
        return 224;
    }

    /**
     * Return the value (as a float) of the field 'converted_voltage_monitoramento'
     */
    public float get_converted_voltage_monitoramento() {
        return (float)getFloatElement(offsetBits_converted_voltage_monitoramento(), 32);
    }

    /**
     * Set the value of the field 'converted_voltage_monitoramento'
     */
    public void set_converted_voltage_monitoramento(float value) {
        setFloatElement(offsetBits_converted_voltage_monitoramento(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_voltage_monitoramento'
     */
    public static int size_converted_voltage_monitoramento() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_voltage_monitoramento'
     */
    public static int sizeBits_converted_voltage_monitoramento() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_voltage_analise
    //   Field type: float, unsigned
    //   Offset (bits): 256
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_voltage_analise' is signed (false).
     */
    public static boolean isSigned_converted_voltage_analise() {
        return false;
    }

    /**
     * Return whether the field 'converted_voltage_analise' is an array (false).
     */
    public static boolean isArray_converted_voltage_analise() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_voltage_analise'
     */
    public static int offset_converted_voltage_analise() {
        return (256 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_voltage_analise'
     */
    public static int offsetBits_converted_voltage_analise() {
        return 256;
    }

    /**
     * Return the value (as a float) of the field 'converted_voltage_analise'
     */
    public float get_converted_voltage_analise() {
        return (float)getFloatElement(offsetBits_converted_voltage_analise(), 32);
    }

    /**
     * Set the value of the field 'converted_voltage_analise'
     */
    public void set_converted_voltage_analise(float value) {
        setFloatElement(offsetBits_converted_voltage_analise(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_voltage_analise'
     */
    public static int size_converted_voltage_analise() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_voltage_analise'
     */
    public static int sizeBits_converted_voltage_analise() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_voltage_planejamento
    //   Field type: float, unsigned
    //   Offset (bits): 288
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_voltage_planejamento' is signed (false).
     */
    public static boolean isSigned_converted_voltage_planejamento() {
        return false;
    }

    /**
     * Return whether the field 'converted_voltage_planejamento' is an array (false).
     */
    public static boolean isArray_converted_voltage_planejamento() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_voltage_planejamento'
     */
    public static int offset_converted_voltage_planejamento() {
        return (288 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_voltage_planejamento'
     */
    public static int offsetBits_converted_voltage_planejamento() {
        return 288;
    }

    /**
     * Return the value (as a float) of the field 'converted_voltage_planejamento'
     */
    public float get_converted_voltage_planejamento() {
        return (float)getFloatElement(offsetBits_converted_voltage_planejamento(), 32);
    }

    /**
     * Set the value of the field 'converted_voltage_planejamento'
     */
    public void set_converted_voltage_planejamento(float value) {
        setFloatElement(offsetBits_converted_voltage_planejamento(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_voltage_planejamento'
     */
    public static int size_converted_voltage_planejamento() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_voltage_planejamento'
     */
    public static int sizeBits_converted_voltage_planejamento() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_voltage_execucao
    //   Field type: float, unsigned
    //   Offset (bits): 320
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_voltage_execucao' is signed (false).
     */
    public static boolean isSigned_converted_voltage_execucao() {
        return false;
    }

    /**
     * Return whether the field 'converted_voltage_execucao' is an array (false).
     */
    public static boolean isArray_converted_voltage_execucao() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_voltage_execucao'
     */
    public static int offset_converted_voltage_execucao() {
        return (320 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_voltage_execucao'
     */
    public static int offsetBits_converted_voltage_execucao() {
        return 320;
    }

    /**
     * Return the value (as a float) of the field 'converted_voltage_execucao'
     */
    public float get_converted_voltage_execucao() {
        return (float)getFloatElement(offsetBits_converted_voltage_execucao(), 32);
    }

    /**
     * Set the value of the field 'converted_voltage_execucao'
     */
    public void set_converted_voltage_execucao(float value) {
        setFloatElement(offsetBits_converted_voltage_execucao(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_voltage_execucao'
     */
    public static int size_converted_voltage_execucao() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_voltage_execucao'
     */
    public static int sizeBits_converted_voltage_execucao() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_voltage_geral
    //   Field type: float, unsigned
    //   Offset (bits): 352
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_voltage_geral' is signed (false).
     */
    public static boolean isSigned_converted_voltage_geral() {
        return false;
    }

    /**
     * Return whether the field 'converted_voltage_geral' is an array (false).
     */
    public static boolean isArray_converted_voltage_geral() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_voltage_geral'
     */
    public static int offset_converted_voltage_geral() {
        return (352 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_voltage_geral'
     */
    public static int offsetBits_converted_voltage_geral() {
        return 352;
    }

    /**
     * Return the value (as a float) of the field 'converted_voltage_geral'
     */
    public float get_converted_voltage_geral() {
        return (float)getFloatElement(offsetBits_converted_voltage_geral(), 32);
    }

    /**
     * Set the value of the field 'converted_voltage_geral'
     */
    public void set_converted_voltage_geral(float value) {
        setFloatElement(offsetBits_converted_voltage_geral(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_voltage_geral'
     */
    public static int size_converted_voltage_geral() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_voltage_geral'
     */
    public static int sizeBits_converted_voltage_geral() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_temperature
    //   Field type: float, unsigned
    //   Offset (bits): 384
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_temperature' is signed (false).
     */
    public static boolean isSigned_converted_temperature() {
        return false;
    }

    /**
     * Return whether the field 'converted_temperature' is an array (false).
     */
    public static boolean isArray_converted_temperature() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_temperature'
     */
    public static int offset_converted_temperature() {
        return (384 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_temperature'
     */
    public static int offsetBits_converted_temperature() {
        return 384;
    }

    /**
     * Return the value (as a float) of the field 'converted_temperature'
     */
    public float get_converted_temperature() {
        return (float)getFloatElement(offsetBits_converted_temperature(), 32);
    }

    /**
     * Set the value of the field 'converted_temperature'
     */
    public void set_converted_temperature(float value) {
        setFloatElement(offsetBits_converted_temperature(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_temperature'
     */
    public static int size_converted_temperature() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_temperature'
     */
    public static int sizeBits_converted_temperature() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: converted_voltage
    //   Field type: float, unsigned
    //   Offset (bits): 416
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'converted_voltage' is signed (false).
     */
    public static boolean isSigned_converted_voltage() {
        return false;
    }

    /**
     * Return whether the field 'converted_voltage' is an array (false).
     */
    public static boolean isArray_converted_voltage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'converted_voltage'
     */
    public static int offset_converted_voltage() {
        return (416 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'converted_voltage'
     */
    public static int offsetBits_converted_voltage() {
        return 416;
    }

    /**
     * Return the value (as a float) of the field 'converted_voltage'
     */
    public float get_converted_voltage() {
        return (float)getFloatElement(offsetBits_converted_voltage(), 32);
    }

    /**
     * Set the value of the field 'converted_voltage'
     */
    public void set_converted_voltage(float value) {
        setFloatElement(offsetBits_converted_voltage(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'converted_voltage'
     */
    public static int size_converted_voltage() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'converted_voltage'
     */
    public static int sizeBits_converted_voltage() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msg_number
    //   Field type: int, unsigned
    //   Offset (bits): 448
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msg_number' is signed (false).
     */
    public static boolean isSigned_msg_number() {
        return false;
    }

    /**
     * Return whether the field 'msg_number' is an array (false).
     */
    public static boolean isArray_msg_number() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'msg_number'
     */
    public static int offset_msg_number() {
        return (448 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msg_number'
     */
    public static int offsetBits_msg_number() {
        return 448;
    }

    /**
     * Return the value (as a int) of the field 'msg_number'
     */
    public int get_msg_number() {
        return (int)getUIntBEElement(offsetBits_msg_number(), 16);
    }

    /**
     * Set the value of the field 'msg_number'
     */
    public void set_msg_number(int value) {
        setUIntBEElement(offsetBits_msg_number(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'msg_number'
     */
    public static int size_msg_number() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'msg_number'
     */
    public static int sizeBits_msg_number() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: node_ID
    //   Field type: int, unsigned
    //   Offset (bits): 464
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'node_ID' is signed (false).
     */
    public static boolean isSigned_node_ID() {
        return false;
    }

    /**
     * Return whether the field 'node_ID' is an array (false).
     */
    public static boolean isArray_node_ID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'node_ID'
     */
    public static int offset_node_ID() {
        return (464 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'node_ID'
     */
    public static int offsetBits_node_ID() {
        return 464;
    }

    /**
     * Return the value (as a int) of the field 'node_ID'
     */
    public int get_node_ID() {
        return (int)getUIntBEElement(offsetBits_node_ID(), 16);
    }

    /**
     * Set the value of the field 'node_ID'
     */
    public void set_node_ID(int value) {
        setUIntBEElement(offsetBits_node_ID(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'node_ID'
     */
    public static int size_node_ID() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'node_ID'
     */
    public static int sizeBits_node_ID() {
        return 16;
    }

}
